version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped 
  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile
    expose:
      - 3000
    depends_on:
      - redis
      - db
    restart: always
    volumes:
      - ./node:/node
  redis:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - ./redis:/redis
    ports:
      - 6379:6379
  db:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./mongo:/mongodb
    ports:
      - 27017:27017 
